# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  ftenwk:

services:

  orderer.free-trade-enterprise.com:
    extends:
      file:   base/docker-compose-base-fte.yaml
      service: orderer.free-trade-enterprise.com
    container_name: orderer.free-trade-enterprise.com
    networks:
      - ftenwk

  peer0.trade-company.free-trade-enterprise.com:
    container_name: peer0.trade-company.free-trade-enterprise.com
    extends:
      file:  base/docker-compose-base-fte.yaml
      service: peer0.trade-company.free-trade-enterprise.com
    networks:
      - ftenwk

  peer1.trade-company.free-trade-enterprise.com:
    container_name: peer1.trade-company.free-trade-enterprise.com
    extends:
      file:  base/docker-compose-base-fte.yaml
      service: peer1.trade-company.free-trade-enterprise.com
    networks:
      - ftenwk

  peer0.bank.com:
    container_name: peer0.bank.com
    extends:
      file:  base/docker-compose-base-fte.yaml
      service: peer0.bank.com
    networks:
      - ftenwk

  peer0.shipping-company.com:
    container_name: peer0.shipping-company.com
    extends:
      file:  base/docker-compose-base-fte.yaml
      service: peer0.shipping-company.com
    networks:
      - ftenwk

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.trade-company.free-trade-enterprise.com:7051
      - CORE_PEER_LOCALMSPID=TradeCompanyMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/trade-company.free-trade-enterprise.com/peers/peer0.trade-company.free-trade-enterprise.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/trade-company.free-trade-enterprise.com/peers/peer0.trade-company.free-trade-enterprise.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/trade-company.free-trade-enterprise.com/peers/peer0.trade-company.free-trade-enterprise.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/trade-company.free-trade-enterprise.com/users/Admin@trade-company.free-trade-enterprise.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY} ${LANG}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.free-trade-enterprise.com
      - peer0.trade-company.free-trade-enterprise.com
      - peer1.trade-company.free-trade-enterprise.com
      - peer0.bank.com
      - peer0.shipping-company.com
    networks:
      - ftenwk
