# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.free-trade-enterprise.com:
    container_name: orderer.free-trade-enterprise.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/free-trade-enterprise.com/orderers/orderer.free-trade-enterprise.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/free-trade-enterprise.com/orderers/orderer.free-trade-enterprise.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.trade-company.free-trade-enterprise.com:
    container_name: peer0.trade-company.free-trade-enterprise.com
    extends:
      file: peer-base-fte.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.trade-company.free-trade-enterprise.com
      - CORE_PEER_ADDRESS=peer0.trade-company.free-trade-enterprise.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.trade-company.free-trade-enterprise.com:7051
      - CORE_PEER_LOCALMSPID=TradeCompanyMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/trade-company.free-trade-enterprise.com/peers/peer0.trade-company.free-trade-enterprise.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/trade-company.free-trade-enterprise.com/peers/peer0.trade-company.free-trade-enterprise.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer1.trade-company.free-trade-enterprise.com:
    container_name: peer1.trade-company.free-trade-enterprise.com
    extends:
      file: peer-base-fte.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.trade-company.free-trade-enterprise.com
      - CORE_PEER_ADDRESS=peer1.trade-company.free-trade-enterprise.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.trade-company.free-trade-enterprise.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.trade-company.free-trade-enterprise.com:7051
      - CORE_PEER_LOCALMSPID=TradeCompanyMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/trade-company.free-trade-enterprise.com/peers/peer1.trade-company.free-trade-enterprise.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/trade-company.free-trade-enterprise.com/peers/peer1.trade-company.free-trade-enterprise.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  peer0.bank.com:
    container_name: peer0.bank.com
    extends:
      file: peer-base-fte.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank.com
      - CORE_PEER_ADDRESS=peer0.bank.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank.com:7051
      - CORE_PEER_LOCALMSPID=BankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank.com/peers/peer0.bank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank.com/peers/peer0.bank.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer0.shipping-company.com:
    container_name: peer0.shipping-company.com
    extends:
      file: peer-base-fte.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.shipping-company.com
      - CORE_PEER_ADDRESS=peer0.shipping-company.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shipping-company.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.shipping-company.com:7051
      - CORE_PEER_LOCALMSPID=ShippingCompanyMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shipping-company.com/peers/peer0.shipping-company.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shipping-company.com/peers/peer0.shipping-company.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
